export { configureORPC, getORPC } from './orpc.js'
export type { ORPCUtils } from './orpc.js'
export { ORPCProvider, useORPC } from './orpc-context.js'
export type { ORPCProviderProps } from './orpc-context.js'

export { getQueryClient, QueryProvider } from './provider.js'
export type { QueryProviderProps } from './provider.js'

// Query hooks
export { useUserName } from './hooks/queries/user/use-user-name.js'
export { useIsUserVerified } from './hooks/queries/user/use-is-user-verified.js'
export { usePreset } from './hooks/queries/preset/use-preset.js'
export { usePresets } from './hooks/queries/preset/use-presets.js'
export { usePresetsByUser } from './hooks/queries/preset/use-preset-by-user.js'
export { useAvatar } from './hooks/queries/use-avatar.js'
export { useExercise } from './hooks/queries/use-exercise.js'
export { useMap } from './hooks/queries/use-map.js'
export { useMedicalHistory } from './hooks/queries/use-medical-history.js'
export {
  useSupplementalTherapyQuery,
  useCreateSupplementalTherapyRelMutation,
} from './hooks/queries/use-supplemental-therapy.js'
export { usePatient } from './hooks/queries/patient/use-patient.js'
export { usePatients } from './hooks/queries/patient/use-patients.js'
export { usePatientSession } from './hooks/queries/patient-session/use-patient-session.js'
export { usePatientSessions } from './hooks/queries/patient-session/use-patient-sessions.js'
export { usePatientProgram } from './hooks/queries/patient-program/use-patient-program.js'
export { usePatientPrograms } from './hooks/queries/patient-program/use-patient-programs.js'
export { useDeviceCore } from './hooks/queries/use-device.js'
export { useWaitlist } from './hooks/queries/waitlist/use-waitlist.js'

// Mutation hooks
export { useCreateProgram } from './hooks/mutations/program/use-create-program.js'
export { useUpdateProgram } from './hooks/mutations/program/use-update-program.js'
export { useDeleteProgram } from './hooks/mutations/program/use-delete-program.js'
export { useCreateProgramExercises } from './hooks/mutations/program-exercise/use-create-program-exercises.js'
export { useUpdateProgramExercises } from './hooks/mutations/program-exercise/use-update-program-exercises.js'
export { useCreatePreset } from './hooks/mutations/preset/use-create-preset.js'
export { useUpdatePreset } from './hooks/mutations/preset/use-update-preset.js'
export { useDeletePreset } from './hooks/mutations/preset/use-delete-preset.js'
export { useCreatePresetExercises } from './hooks/mutations/preset-exercise/use-create-preset-exercises.js'
export { useUpdatePresetExercises } from './hooks/mutations/preset-exercise/use-update-preset-exercises.js'
export { useNewPatient } from './hooks/mutations/patient/use-new-patient.js'
export { useUpdatePatient } from './hooks/mutations/patient/use-update-patient.js'
export { useDeletePatient } from './hooks/mutations/patient/use-delete-patient.js'
export { useCreatePatientSession } from './hooks/mutations/patient-session/use-create-patient-session.js'
export { useUpdatePatientSession } from './hooks/mutations/patient-session/use-update-patient-session.js'
export { useDeletePatientSession } from './hooks/mutations/patient-session/use-delete-patient-session.js'
export { useCompleteSession } from './hooks/mutations/patient-session/use-complete-session.js'
export { useCreatePatientSessionData } from './hooks/mutations/patient-session-data/use-create-patient-session-data.js'
export { useCreatePatientSessionExercises } from './hooks/mutations/patient-session-exercise/use-create-patient-session-exercises.js'
export { useSetDeviceId } from './hooks/mutations/device/use-set-device-id.js'
export { useResetDeviceId } from './hooks/mutations/device/use-reset-device-id.js'
export { useCreateWaitlist } from './hooks/mutations/waitlist/use-create-waitlist.js'
